version : "3.9"

services:

  nginx:
    image : nginx:for_inception
    container_name : nginx
    build : ./requirements/nginx/
    ports :
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - incep_network
    restart : always

  mariadb:
    image : mariadb:for_inception
    container_name : mariadb
    build : ./requirements/mariadb/
    expose :
     - "3306"
    networks:
      - incep_network
    volumes:
      - mariadb:/var/lib/mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart : always

  wordpress:
    image : wordpress:for_inception
    container_name : wordpress
    build : ./requirements/wordpress/
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - incep_network
    volumes:
          - wordpress:/var/www/html
    env_file: ./.env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PWD: ${WP_PWD}
      WP_DATABASE_USER: ${WP_DATABASE_USER}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
    restart : always

networks:
  incep_network:

volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/ael-khat/data/for_wordpress
      o: bind

  mariadb:
    driver_opts:
      type: none
      device: /home/ael-khat/data/for_mariadb
      o: bind
